package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"app/ent"
	"app/gen"
	"context"

	"github.com/google/uuid"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id uuid.UUID) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []uuid.UUID) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// Articles is the resolver for the articles field.
func (r *queryResolver) Articles(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int, orderBy *ent.ArticleOrder, where *ent.ArticleWhereInput) (*ent.ArticleConnection, error) {
	return r.client.Article.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithArticleOrder(orderBy),
		)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*ent.Category, error) {
	return r.client.Category.Query().All(ctx)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int, orderBy *ent.CommentOrder, where *ent.CommentWhereInput) (*ent.CommentConnection, error) {
	return r.client.Comment.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithCommentOrder(orderBy),
		)
}

// Galleries is the resolver for the galleries field.
func (r *queryResolver) Galleries(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int, orderBy *ent.GalleryOrder, where *ent.GalleryWhereInput) (*ent.GalleryConnection, error) {
	return r.client.Gallery.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithGalleryOrder(orderBy),
		)
}

// Metadata is the resolver for the METADATA field.
func (r *queryResolver) Metadata(ctx context.Context) ([]*ent.Metadata, error) {
	return r.client.Metadata.Query().All(ctx)
}

// Newsletters is the resolver for the newsletters field.
func (r *queryResolver) Newsletters(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int, orderBy *ent.NewsletterOrder, where *ent.NewsletterWhereInput) (*ent.NewsletterConnection, error) {
	return r.client.Newsletter.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithNewsletterOrder(orderBy),
		)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*ent.Tag, error) {
	return r.client.Tag.Query().All(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *ent.Cursor, first *int, before *ent.Cursor, last *int, orderBy *ent.UserOrder, where *ent.UserWhereInput) (*ent.UserConnection, error) {
	return r.client.User.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithUserOrder(orderBy),
		)
}

// Query returns gen.QueryResolver implementation.
func (r *Resolver) Query() gen.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
