// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/gallery"
	"app/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GalleryDelete is the builder for deleting a Gallery entity.
type GalleryDelete struct {
	config
	hooks    []Hook
	mutation *GalleryMutation
}

// Where appends a list predicates to the GalleryDelete builder.
func (gd *GalleryDelete) Where(ps ...predicate.Gallery) *GalleryDelete {
	gd.mutation.Where(ps...)
	return gd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gd *GalleryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, GalleryMutation](ctx, gd.sqlExec, gd.mutation, gd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gd *GalleryDelete) ExecX(ctx context.Context) int {
	n, err := gd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gd *GalleryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gallery.Table, sqlgraph.NewFieldSpec(gallery.FieldID, field.TypeUUID))
	if ps := gd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gd.mutation.done = true
	return affected, err
}

// GalleryDeleteOne is the builder for deleting a single Gallery entity.
type GalleryDeleteOne struct {
	gd *GalleryDelete
}

// Where appends a list predicates to the GalleryDelete builder.
func (gdo *GalleryDeleteOne) Where(ps ...predicate.Gallery) *GalleryDeleteOne {
	gdo.gd.mutation.Where(ps...)
	return gdo
}

// Exec executes the deletion query.
func (gdo *GalleryDeleteOne) Exec(ctx context.Context) error {
	n, err := gdo.gd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gallery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gdo *GalleryDeleteOne) ExecX(ctx context.Context) {
	if err := gdo.Exec(ctx); err != nil {
		panic(err)
	}
}
