// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Article) Categories(ctx context.Context) (result []*Category, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = a.NamedCategories(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = a.Edges.CategoriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = a.QueryCategories().All(ctx)
	}
	return result, err
}

func (c *Category) Article(ctx context.Context) (result []*Article, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = c.NamedArticle(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = c.Edges.ArticleOrErr()
	}
	if IsNotLoaded(err) {
		result, err = c.QueryArticle().All(ctx)
	}
	return result, err
}
